"""
Converts a Shopify product export CSV into data/products.js for the site.
Usage (from the project root):
    python3 scripts/csv_to_products.py data/products_export.csv
"""
import csv, html, json, re, sys
from collections import OrderedDict

SRC = sys.argv[1] if len(sys.argv) > 1 else "data/products_export.csv"
OUT = "data/products.js"

def category(handle, title, cat):
    t = (handle + " " + title + " " + (cat or "")).lower()
    if "oil" in t: return "Oils"
    if "shilajit" in t or "salajeet" in t: return "Shilajit"
    if any(k in t for k in ["ring", "necklace", "pendant", "jewelry", "bracelet", "silver set"]): return "Jewellery"
    if any(k in t for k in ["cap", "topi", "shirt", "tunic", "shawl", "kurta", "dress"]): return "Clothing & Caps"
    if "gift box" in t or "gift-box" in t: return "Crafts & Gifts"
    if any(k in t for k in ["sattu", "buckwheat", "flour"]): return "Grains & Flour"
    return "Dry Fruits & Nuts"

def clean_text(raw):
    if not raw: return ""
    txt = re.sub(r"<(br|/p|/li|/h\d)[^>]*>", "\n", raw, flags=re.I)
    txt = re.sub(r"<[^>]+>", "", txt)
    txt = html.unescape(txt)
    lines = [re.sub(r"\s+", " ", l).strip() for l in txt.split("\n")]
    return "\n".join(l for l in lines if l)

def short_name(title):
    for sep in [" | ", " – ", " - "]:
        if sep in title:
            head, tail = title.split(sep, 1)
            return re.sub(r"\s+", " ", head).strip(), re.sub(r"\s+", " ", tail).strip()
    return re.sub(r"\s+", " ", title).strip(), ""

def num(v):
    try: return float(v)
    except (TypeError, ValueError): return None

products = OrderedDict()
with open(SRC, newline="", encoding="utf-8-sig") as f:
    for row in csv.DictReader(f):
        h = row["Handle"].strip()
        if h not in products:
            if (row.get("Status") or "").strip() not in ("active", ""):  # skip drafts/archived
                products[h] = None
                continue
            name, sub = short_name(row["Title"])
            products[h] = {
                "id": h, "name": name, "subtitle": sub,
                "category": category(h, row["Title"], row.get("Product Category")),
                "description": clean_text(row["Body (HTML)"]),
                "optionNames": [row.get(f"Option{i} Name", "").strip().capitalize()
                                for i in (1, 2, 3) if row.get(f"Option{i} Name", "").strip()],
                "images": [], "variants": [],
            }
        p = products[h]
        if p is None: continue
        img = (row.get("Image Src") or "").strip()
        if img and img not in p["images"]: p["images"].append(img)
        price = num(row.get("Variant Price"))
        if price is not None:
            vals = [row.get(f"Option{i} Value", "").strip() for i in (1, 2, 3)]
            vals = [v for v in vals if v and v != "Default Title"]
            compare = num(row.get("Variant Compare At Price"))
            p["variants"].append({
                "values": vals,
                "price": round(price),
                "compareAt": round(compare) if compare and compare > price else None,
            })

out = []
for p in products.values():
    if not p or not p["variants"]: continue
    # hide option columns that never change (e.g. "wool" on every shawl variant)
    n = max(len(v["values"]) for v in p["variants"])
    keep = [i for i in range(n) if len({(v["values"][i] if i < len(v["values"]) else "") for v in p["variants"]}) > 1]
    if len(p["variants"]) == 1: keep = []
    p["optionNames"] = [p["optionNames"][i] for i in keep if i < len(p["optionNames"])]
    for v in p["variants"]:
        v["label"] = " / ".join(v["values"][i] for i in keep if i < len(v["values"]))
        del v["values"]
    seen, uniq = set(), []
    for v in p["variants"]:
        k = (v["label"], v["price"])
        if k not in seen: seen.add(k); uniq.append(v)
    p["variants"] = uniq
    if all(not v["label"] for v in uniq): p["optionNames"] = []
    out.append(p)

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/csv_to_products.py. Edit the CSV and re-run instead of editing by hand.\n")
    f.write("window.PRODUCTS = " + json.dumps(out, ensure_ascii=False, indent=2) + ";\n")
print(f"Wrote {len(out)} products to {OUT}")
